spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:postgresql://localhost:5433/audit_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    listener:
      ack-mode: manual

    consumer:
      group-id: audit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.json.type.mapping: "com.Matheus.task_service.messaging.event.TaskCreatedEvent:com.Matheus.audit_service.messaging.event.TaskCreatedEvent,com.Matheus.task_service.messaging.event.TaskStatusChangedEvent:com.Matheus.audit_service.messaging.event.TaskStatusChangedEvent,com.Matheus.task_service.messaging.event.TaskPriorityChangedEvent:com.Matheus.audit_service.messaging.event.TaskPriorityChangedEvent,com.Matheus.task_service.messaging.event.TaskUpdatedEvent:com.Matheus.audit_service.messaging.event.TaskUpdatedEvent,com.Matheus.task_service.messaging.event.TaskDeletedEvent:com.Matheus.audit_service.messaging.event.TaskDeletedEvent"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer